image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker-readonly
    - us-east-1
    - sandbox
  script:
    - cd app
    - npm ci --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - app/dist/
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - app/node_modules/

pages:
  stage: deploy
  tags:
    - docker-readonly
    - us-east-1
    - sandbox
  script:
    - rm -rf public
    - cp -r app/dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - main
