image: node:22.14.0

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd app
    - npm ci
    - npm run build
  artifacts:
    paths:
      - app/dist

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r app/dist/* public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
